CGI-OPEN-ENT-NG/entcore-css-lib

- scss/specifics/calendar/_calendar.scss
- scss/specifics/calendar/components/_icons.scss
- scss/specifics/calendar/components/sidebar.scss
changes from calendar dev branch
> feat(calendar): update calendar with dev changes

- scss/specifics/minibadge/_minibadge.scss
- scss/specifics/minibadge/components/_icon.scss
> fix(minibadge): #MBA-36 fix icons for minibadge

- scss/specifics/minibadge/components/_card.scss
- scss/specifics/minibadge/components/_container.scss
- scss/specifics/minibadge/containers/_statistics.scss
Récupération de la liste des types les moins assignés (css front)
> feat(statistics-metrics): #MBA-86 get list less type assigned front

- scss/specifics/minibadge/containers/_statistics.scss
Modification du style de la liste des utilisateurs ayant le plus reçus de badges
> feat(statistics-metrics): #MBA-89 get list most assigning and most receiving users front

- scss/specifics/minibadge/_minibadge.scss
- scss/specifics/minibadge/components/_container-header.scss
- scss/specifics/minibadge/components/_index.scss
- scss/specifics/minibadge/components/_navbar.scss
- scss/specifics/minibadge/components/_type.scss
- scss/specifics/minibadge/containers/_container.scss
Edition du bouton d'ouverture de la charte de validation du module
> feat(chart): #MBA-78 change opening chart button style front

- scss/specifics/minibadge/components/_card.scss
Désactiver visuellement les cartes lorsque la charte n'est pas accepté.
> feat(chart): #MBA-95 disable card (style) when chart is not accepted

- scss/specifics/formulaire/components/containers/cursor/_question-type-cursor.scss
I made three differents 3 commits on the same branch by mistake so exceptionally I have the authorization to make only one PR because tickets are all linked: they concern the custom of input type range.
> feat(formulaire): #FOR-457/500/523 improve input design

- scss/specifics/minibadge/components/_list.scss
- scss/specifics/minibadge/components/_user-list.scss
Correction de l'affichage des avatars utilisateur
> fix(type): #MBA-83 fix avatar style

- scss/specifics/minibadge/_mixins.scss
Ajout d'une classe pour le curseur par défaut.
en lien avec la PR de minibadge: https://github.com/CGI-OPEN-ENT-NG/minibadge/pull/68
> fix(card): #MBA-100 add default cursor class

- scss/specifics/magneto/_mixins.scss
- scss/specifics/magneto/components/_icons.scss
- scss/specifics/magneto/components/containers/_board.scss
- scss/specifics/magneto/components/directives/_board-manage-lightbox.scss
- scss/specifics/magneto/components/directives/_card-list-item.scss
Add properties layout to board with three new icons
linked with magneto PR : https://github.com/CGI-OPEN-ENT-NG/magneto/pull/54
> feat(section): #MAG-102 add layout properties in boards

- scss/specifics/magneto/_mixins.scss
- scss/specifics/magneto/components/_index.scss
- scss/specifics/magneto/components/_scrollbar.scss
- scss/specifics/magneto/components/containers/_board.scss
- scss/specifics/magneto/components/directives/_card-list.scss
- scss/specifics/magneto/components/directives/_index.scss
- scss/specifics/magneto/components/directives/_section-list.scss
- Add sections class to show section in board view
- Add scrollbar class to have a new design
- Add new screen size to have responsive section
> feat(section): #MAG-103 add sections

- scss/specifics/minibadge/containers/_statistics.scss
Assure que les éléments composants une liste restent alignés.
[PR - Minibadge](https://github.com/CGI-OPEN-ENT-NG/minibadge/pull/76)
> fix(statistics): #MBA-105 fix lists style to keep elements aligned.

- scss/specifics/minibadge/components/_given-array.scss
- scss/specifics/minibadge/components/_periode-picker.scss
- scss/specifics/minibadge/containers/_badge-given.scss
Correction de l'alignement des sélecteurs de filtre (date picker / search filter)
> fix(badge-given): #MBA-107 fix filter elements alignment

- scss/specifics/magneto/components/containers/_board.scss
- scss/specifics/magneto/components/directives/_board-manage-lightbox.scss
- scss/specifics/magneto/components/directives/_card-list.scss
- scss/specifics/magneto/components/directives/_section-list.scss
add drag and drop styles :
- min height/width to add new cards to an empty section
- separate board layout config to be more clear
https://jira.support-ent.fr/browse/MAG-104
> feat(section): #MAG-104 add drag and drop

- scss/specifics/magneto/_mixins.scss
- scss/specifics/magneto/components/_icons.scss
- scss/specifics/magneto/components/containers/_board-read.scss
- scss/specifics/magneto/components/directives/_card-list-item.scss
- scss/specifics/magneto/components/directives/_card-list.scss
- scss/specifics/magneto/components/directives/_section-list.scss
- Add icons for lock/unlock card
- Add responsive screen size for section
- Add reading mode css for sections
Linked PR :
- MAG 94 : https://github.com/CGI-OPEN-ENT-NG/magneto/pull/62
- MAG 117 : https://github.com/CGI-OPEN-ENT-NG/magneto/pull/66
- MAG 123 : https://github.com/CGI-OPEN-ENT-NG/magneto/pull/65
> feat(section): #MAG-94 117 123 add lock card + responsive section + reading mode

- scss/specifics/statistics-presences/indicators/_global.scss
Sur la vue indicateur global, correction du background de la ligne des totaux, afin qu'elle passe au dessus de tout le reste.
> fix(statistics): #MA-1088 fix totals line background on global statistics view.

- scss/specifics/magneto/components/_icons.scss
- scss/specifics/magneto/components/_scrollbar.scss
- scss/specifics/magneto/components/containers/_board.scss
- scss/specifics/magneto/components/directives/_board-manage-lightbox.scss
- scss/specifics/magneto/components/directives/_card-list.scss
- Add icon user to have owner of the board
- Add background image manage
Tickets :
- https://jira.support-ent.fr/browse/MAG-137
- https://jira.support-ent.fr/browse/MAG-22
Linked to PR:
https://github.com/CGI-OPEN-ENT-NG/magneto/pull/75
> feat(board): #MAG-22 add board background image

- scss/specifics/minibadge/components/_icon.scss
sur les listes des badges me concernant:
- l'icone "planète" deviens "œil"
- l'icone "cadenas" deviens "œil barré"
https://github.com/OPEN-ENT-NG/minibadge/pull/12
> fix(badges): #MBA-126 change icons for badge status

- scss/specifics/formulaire/components/_icon.scss
Add "restore" icon
FOR-513 : https://jira.support-ent.fr/browse/FOR-513
https://github.com/OPEN-ENT-NG/form/pull/203
> feat(formulaire): [#FOR-513] add a new icon

- scss/specifics/lystore/components/parameter/_parameter-active-structure.scss
align checkbox in active structure parameter
> fix(Lystore-Parameter)#MLYSTORE-664:align checkbox

- scss/specifics/minibadge/containers/_statistics.scss
Style s'adaptant à l'ajout du nombre de fois qu'un badge a été supprimé.
> fix(badges): #MBA-122 add times refused number

- scss/specifics/formulaire/components/_icon.scss
Add class to hover cursor for duplicate, delete and cancel buttons
[FOR-537](https://jira.support-ent.fr/browse/FOR-537)
https://github.com/OPEN-ENT-NG/form/pull/207
> feat(formulaire): #FOR-537 add cursor pointer

- scss/specifics/magneto/components/_icons.scss
- scss/specifics/magneto/components/containers/_board-read.scss
- scss/specifics/magneto/components/containers/_board.scss
- scss/specifics/magneto/components/directives/_board-manage-lightbox.scss
- scss/specifics/magneto/components/directives/_card-collection-lightbox.scss
- scss/specifics/magneto/components/directives/_card-comment.scss
- scss/specifics/magneto/components/directives/_card-item-comments.scss
- scss/specifics/magneto/components/directives/_card-list-item-options.scss
- scss/specifics/magneto/components/directives/_card-list-item.scss
- scss/specifics/magneto/components/directives/_card-list.scss
- scss/specifics/magneto/components/directives/_card-manage-lightbox.scss
- scss/specifics/magneto/components/directives/_comments-panel.scss
- scss/specifics/magneto/components/directives/_index.scss
- scss/specifics/magneto/components/directives/_section-list.scss
Voir les PRs : 
https://github.com/CGI-OPEN-ENT-NG/magneto/pull/76
https://github.com/CGI-OPEN-ENT-NG/magneto/pull/77
https://github.com/CGI-OPEN-ENT-NG/magneto/pull/82
> feat(magneto): #MAG-41/MAG-166 add card comments + fix card display

- scss/specifics/crre/_crre.scss
Voir la PR https://github.com/CGI-OPEN-ENT-NG/crre/pull/63
> feat: #CRRE-499 add dynamic display for price for validator

- scss/specifics/crre/_crre.scss
- scss/specifics/crre/components/_icons.scss
- scss/specifics/crre/components/_index.scss
Voir https://github.com/CGI-OPEN-ENT-NG/crre/pull/81
> feat(admin): #CRRE-489 add header sorting for admin orders

- scss/specifics/formulaire/components/containers/cursor/_question-type-cursor.scss
- Cursor response now has pin following the cursor
- Cursor question spacing on creation side are improved
> fix(formulaire): [#FOR-565] improve cursors

- scss/specifics/formulaire/components/_main.scss
- scss/specifics/formulaire/components/_result-form.scss
Add specificity for cursor's graph + create new file to manage generals classes
[FOR-584](https://jira.support-ent.fr/browse/FOR-584)
https://github.com/OPEN-ENT-NG/form/pull/236
> feat(formulaire): #FOR-584 adapt cursor's graph

- scss/specifics/crre/_crre.scss
Add list box display as flex for duplicated orders
Link to :
https://github.com/CGI-OPEN-ENT-NG/crre/pull/98
https://github.com/CGI-OPEN-ENT-NG/crre/pull/99
> feat(crre): #CRRE-494 add duplicated orders info

- scss/specifics/calendar/components/calendar.scss
Creates a new calendar scss file and adapts CRNA css so its fits more with the red theme.
To merge with : https://github.com/OPEN-ENT-NG/theme-open-ent/pull/38
> fix(calendar) : MC-118 Adapts CRNA css so its fits more with the red theme.

- scss/specifics/presences/components/_index.scss
- scss/specifics/presences/components/_init-teachers-lightbox.scss
- add CSS for Présences Init Popup for listing teachers with no classes
> feat(presences): #MA-1067 add initialization teachers check form

- scss/specifics/formulaire/components/_edit-form.scss
Add next_form_element css for section
> fix(formulaire): [#FOR-531] add next_form_element css for section

- scss/specifics/presences/components/containers/_calendar.scss
Fix issue where names were replaces by "..." when to long.
> fix(nameDisplay): MA-1094 fix name replaced by "..."

- scss/specifics/competences/components/_competences.scss
##Describe your changes
Modifie la pop-up permettant d'ajouter un filtre à la pop-up du suivis des acquis.
https://github.com/OPEN-ENT-NG/competences/pull/223
> feat(class-council): #EVAL-339 change achievements monitoring filter popup style

- scss/specifics/crre/_crre.scss
Voir https://github.com/OPEN-ENT-NG/crre/pull/4
> fix(css): #CRRE-594 fix campaign display name on admin page

- scss/specifics/magneto/components/containers/_board.scss
PR CSS : https://github.com/OPEN-ENT-NG/magneto/pull/2
> fix(board): #MAG-128 line breaks are displayed in board description

- scss/specifics/magneto/components/directives/_board-list-item.scss
Modify scss board list to proprify it.
Ticket Jira : [MAG-90](https://jira.support-ent.fr/browse/MAG-90)
> feat(boardList): #MAG-90 modify design of board list

- scss/specifics/magneto/components/containers/_board.scss
- scss/specifics/magneto/components/directives/_board-nav.scss
Linked with this PR : 
https://github.com/OPEN-ENT-NG/magneto/pull/7
> feat(boardNav): #MAG-182 change responsive for navbar

- scss/specifics/magneto/components/containers/_board.scss
Modify responsive for mobile view
Old view :
New view :
> feat(boardNav): #MAG-182 modify responsive for mobile view

- scss/specifics/formulaire/components/containers/_index.scss
- scss/specifics/formulaire/components/containers/tree/_tree.scss
We now can see the workflow of a form represented by nodes and arrows.
LINKED with PR : https://github.com/OPEN-ENT-NG/form/pull/279
> Feat(editForm): #FOR-633 add vue to display form workflow"

- scss/specifics/crre/fragments/_status-circle.scss
Voir https://github.com/OPEN-ENT-NG/crre/pull/14
> feat: #CRRE-606 make non historical order archived during bookseller transition

- scss/specifics/formulaire/components/_edit-form.scss
- scss/specifics/formulaire/components/_icon.scss
- scss/specifics/formulaire/components/_respond-question.scss
Display images in differents views : create / respond / recap / public
[FOR-343](https://jira.support-ent.fr/browse/FOR-343)
Sous-tickets [FOR-656](https://jira.support-ent.fr/browse/FOR-656) & [FOR-657](https://jira.support-ent.fr/browse/FOR-657)
https://github.com/OPEN-ENT-NG/form/pull/285
> feat(formulaire): #FOR-343 add image in questionTypeMultipleAnswer

- scss/specifics/formulaire/components/_respond-question.scss
Display images in differents views : respond / recap / public
[FOR-669](https://jira.support-ent.fr/browse/FOR-669)
https://github.com/OPEN-ENT-NG/form/pull/295
> feat(formulaire): #FOR-669 update respond view singleanswerradio
